replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/project-52700b7f-e48a-4255-bd4/tele-call/alert-caller
  tag: "v2"
  pullPolicy: Always

namespace: alert-caller

env:
  timezone: "Asia/Ho_Chi_Minh"

telegram:
  credentialsSecret: telegram-credentials
  sessionSecret: telegram-session

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

oncall:
  group_chat_id: "-1003940071694"

  call_on_severities:
    - disaster

  call_on_namespace_patterns:
    - ".*-production"

  call_on_receivers:
    - telegram-nginx-upstream-logs
    - nginx-telegram
    - postgresql-telegram
    - telegram-ambassador-ratelimit
    - telegram-ambassador-request
    - telegram-ambassador-response-code
    - telegram-ambassador-sql-injection
    - telegram-application-logs
    - telegram-nginx-logs
    - telegram-nginx-upstream-logs-critical
    - telegram-postgresql-cpu
    - telegram-postgresql-storage
    - dr-vm-disk-telegram
    - dr-vm-telegram
    - etcd-telegram
    - infra-telegram
    - infra-telegram-critical
    - platform-k8s-node-telegram
    - platform-k8s-node-telegram-critical
    - platform-telegram
    - postgresql-dr-telegram
    - prod-cassandra-telegram
    - prod-k8s-app-container-telegram
    - prod-k8s-app-container-telegram-critical
    - prod-k8s-app-pod-telegram
    - prod-k8s-app-pod-telegram-critical
    - prod-k8s-app-telegram
    - prod-k8s-cert-monitor-telegram
    - prod-k8s-plf-container-telegram
    - prod-k8s-plf-container-telegram-critical
    - prod-k8s-plf-pod-telegram
    - prod-k8s-plf-pod-telegram-critical
    - prod-k8s-pvc-telegram
    - prod-redis-telegram
    - prod-temporal-telegram
    - rabbitmq-telegram
    - ratelimit-hook
    - strongswan-telegram
    - vm-disk-stg-telegram
    - vm-disk-telegram
    - vm-reboot-telegram-dc-prod
    - vm-reboot-telegram-dr
    - vm-telegram

  schedule:
    - name: "DevOps Hieudd"
      telegram: "@duchieu246"
      user_id: 1640658111
      days: [2, 3, 4, 5, 6]
      hours:
        - start: "08:30"
          end: "18:30"

    - name: "coach Quynh"
      telegram: "@xuanquynhqbf"
      user_id: 765199915
      days: [2, 3, 4, 5, 6]
      hours:
        - start: "08:30"
          end: "18:30"

    - name: "DevOps Tuanpv"
      telegram: "@tuanphi2408"
      user_id: 6495513678
      days: [2, 3, 4, 5, 6]
      hours:
        - start: "08:30"
          end: "18:30"