replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/project-52700b7f-e48a-4255-bd4/tele-call/alert-caller
  tag: "v2"
  pullPolicy: Always

namespace: alert-caller

env:
  timezone: "Asia/Ho_Chi_Minh"

telegram:
  credentialsSecret: telegram-credentials
  sessionSecret: telegram-session

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

oncall:
  group_chat_id: "-1003940071694"

  # Chỉ xử lý alert có severity = disaster
  call_on_severities:
    - disaster

  # K8s alert: chỉ gọi khi namespace match pattern này
  # Infrastructure alert (không có namespace): gọi luôn
  call_on_namespace_patterns:
    - ".*-production"

  # Chỉ gọi khi alert đến từ các receiver này
  call_on_receivers:
    - postgresql-telegram
    - vm-telegram
    - vm-telegram-prod
    - vm-disk-telegram
    - vm-disk-telegram-prod
    - etcd-telegram
    - k8s-pod-telegram
    - k8s-container-telegram
    - infra-telegram
    - infra-telegram-prod
    - strongswan-telegram
    - redis-telegram
    - gatus-telegram
    - prod-cassandra-telegram

  schedule:
    - name: "DevOps Hieudd"
      telegram: "@duchieu246"
      user_id: 1640658111
      days: [2, 3, 4, 5, 6]
      hours:
        - start: "08:30"
          end: "18:30"

    - name: "coach Quynh"
      telegram: "@xuanquynhqbf"
      user_id: 765199915
      days: [2, 3, 4, 5, 6]
      hours:
         - start: "08:30"
           end: "18:30"
 
    - name: "DevOps Tuanpv"
      telegram: "@tuanphi2408"
      user_id: 6495513678
      days: [2, 3, 4, 5, 6]
      hours:
        - start: "08:30"
          end: "18:30"