replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/project-52700b7f-e48a-4255-bd4/tele-call/alert-caller
  tag: "v2"
  pullPolicy: Always

namespace: alert-caller

env:
  timezone: "Asia/Ho_Chi_Minh"

telegram:
  credentialsSecret: telegram-credentials
  sessionSecret: telegram-session

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

oncall:
  group_chat_id: "-1003940071694"
  schedule:
    - name: "hieudd"
      telegram: "@SeanNG21"
      user_id: 2014724625
      days: [2, 3, 4, 5, 6]
      hours:
        - start: "08:30"
          end: "23:30"

    # - name: "coach Quynh"
    #   telegram: "@xuanquynhqbf"
    #   user_id: 765199915
    #   days: [7, 8]
    #   hours:
    #     - start: "08:30"
    #       end: "23:30"

    # - name: "tuan"
    #   telegram: "@tuanphi2408"
    #   user_id: 6495513678
    #   days: [2, 3, 4, 5, 6]
    #   hours:
    #     - start: "08:30"
    #       end: "23:30"