apiVersion: v1
kind: ConfigMap
metadata:
  name: oncall-config
  namespace: {{ .Values.namespace }}
data:
  oncall.yaml: |
    group_chat_id: {{ .Values.oncall.group_chat_id | quote }}
    call_on_alerts:
    {{- range .Values.oncall.call_on_alerts }}
      - {{ . }}
    {{- end }}
    schedule:
    {{- range .Values.oncall.schedule }}
      - name: {{ .name | quote }}
        telegram: {{ .telegram | quote }}
        user_id: {{ .user_id }}
        days: {{ .days | toJson }}
        hours:
        {{- range .hours }}
          - start: {{ .start | quote }}
            end: {{ .end | quote }}
        {{- end }}
    {{- end }}