apiVersion: v1
kind: ConfigMap
metadata:
  name: oncall-config
  namespace: {{ .Values.namespace }}
data:
  oncall.yaml: |
    schedule:
    {{- range .Values.oncall.schedule }}
      - name: {{ .name | quote }}
        telegram: {{ .telegram | quote }}
        days: {{ .days | toJson }}
        hours:
        {{- range .hours }}
          - start: {{ .start | quote }}
            end: {{ .end | quote }}
        {{- end }}
    {{- end }}