apiVersion: v1
kind: Secret
metadata:
  name: telegram-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  api_id: {{ .Values.telegram.apiId | quote }}
  api_hash: {{ .Values.telegram.apiHash | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: telegram-session-string
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  session_string: {{ .Values.telegram.sessionString | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-token
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  token: {{ .Values.webhookToken | quote }}
