[postgres]
postgres-vm

[postgres:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="gcloud compute start-iap-tunnel postgres-vm 22 --listen-on-stdin --zone=us-central1-a --project=project-52700b7f-e48a-4255-bd4"'
ansible_user=hieudd
ansible_ssh_private_key_file=~/.ssh/google_compute_engine
