---
- name: Setup PostgreSQL database and user
  hosts: postgres
  become: true

  tasks:
    - name: Create database g-pay
      shell: sudo -u postgres psql -c "CREATE DATABASE \"g-pay\";"
      ignore_errors: yes

    - name: Create user hieudd
      shell: sudo -u postgres psql -c "CREATE USER hieudd WITH PASSWORD 'changeme123';"
      ignore_errors: yes

    - name: Grant all privileges on g-pay to hieudd
      shell: sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE \"g-pay\" TO hieudd;"
      ignore_errors: yes

    - name: Update password for hieudd
      shell: sudo -u postgres psql -c "ALTER USER hieudd WITH PASSWORD 'abc@123';"
      ignore_errors: yes