---
- name: Install PostgreSQL
  hosts: postgres
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present

    - name: Start and enable PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes
